// Why: pi has no settings.json hook surface — its extensibility is the
// in-process TypeScript extension API (pi.on('agent_start'), 'tool_call',
// etc.). To get pi panes into the unified agent-hooks pipeline alongside
// Claude/Codex/Gemini/OpenCode/Cursor, we ship a bundled extension into
// the selected Pi/OMP extension dir (PiTitlebarExtensionService) that POSTs to
// /hook/<kind> using the same ORCA_AGENT_HOOK_* + ORCA_PANE_KEY env that every
// PTY already receives from ipc/pty.ts.
//
// Each Pi process gets its own paneKey through env. Like the OpenCode plugin,
// the returned source is a string (loaded by jiti from disk inside the pi process), so we
// keep the source body in plain JS without TS types and avoid pulling pi or
// any Orca dep into the pi runtime.
import type { PiAgentKind } from '../../shared/pi-agent-kind'
import { getPiAgentStatusHandlerSourceLines } from './agent-status-handler-source'
import { getPiAgentStatusRuntimeDetectionSourceLines } from './agent-status-runtime-detection-source'

export const ORCA_PI_AGENT_STATUS_EXTENSION_FILE = 'orca-agent-status.ts'

export function getPiAgentStatusExtensionSource(kind: PiAgentKind = 'pi'): string {
  // Why: OMP needs the file only to reject ephemeral sessions; disclose just its resume id.
  const sessionMetadataSourceLines =
    kind === 'pi'
      ? [
          'let sessionMetadata: Record<string, unknown> = {}',
          'let runtimeOmpSessionMetadata: Record<string, unknown> = {}',
          '',
          'function updateSessionMetadata(ctx: unknown): void {',
          '  const sessionManager = (ctx as { sessionManager?: { getSessionId?: () => unknown; getSessionFile?: () => unknown } } | null)?.sessionManager',
          '  const sessionId = sessionManager?.getSessionId?.()',
          '  const sessionFile = sessionManager?.getSessionFile?.()',
          "  sessionMetadata = typeof sessionId === 'string' && sessionId ? {",
          '    session_id: sessionId,',
          "    ...(typeof sessionFile === 'string' && sessionFile ? { session_file: sessionFile } : {}),",
          '  } : {}',
          '}',
          '',
          'function updateRuntimeOmpSessionMetadata(ctx: unknown): void {',
          '  if (!isOmpRuntime()) return',
          '  const sessionManager = (ctx as { sessionManager?: { getSessionId?: () => unknown; getSessionFile?: () => unknown } } | null)?.sessionManager',
          '  const sessionId = sessionManager?.getSessionId?.()',
          '  const sessionFile = sessionManager?.getSessionFile?.()',
          "  runtimeOmpSessionMetadata = typeof sessionId === 'string' && sessionId && typeof sessionFile === 'string' && sessionFile ? { session_id: sessionId } : {}",
          '}',
          '',
          'function getPostSessionMetadata(ompRuntime: boolean): Record<string, unknown> {',
          '  return ompRuntime ? runtimeOmpSessionMetadata : sessionMetadata',
          '}',
          '',
          'function getPersistedSessionMetadata(): Record<string, unknown> {',
          '  const sessionFile = sessionMetadata.session_file',
          "  if (typeof sessionFile !== 'string' || !sessionFile) return {}",
          '  try {',
          "    const fs = require('fs')",
          '    // Why: Pi publishes its planned path before creating the transcript;',
          '    // recheck on every post so the first completed turn becomes resumable.',
          '    return fs.existsSync(sessionFile) ? sessionMetadata : {}',
          '  } catch {',
          '    return {}',
          '  }',
          '}',
          ''
        ]
      : [
          'let sessionMetadata: Record<string, unknown> = {}',
          '',
          'function updateSessionMetadata(ctx: unknown): void {',
          '  const sessionManager = (ctx as { sessionManager?: { getSessionId?: () => unknown; getSessionFile?: () => unknown } } | null)?.sessionManager',
          '  const sessionId = sessionManager?.getSessionId?.()',
          '  const sessionFile = sessionManager?.getSessionFile?.()',
          "  sessionMetadata = typeof sessionId === 'string' && sessionId && typeof sessionFile === 'string' && sessionFile ? { session_id: sessionId } : {}",
          '}',
          '',
          'function updateRuntimeOmpSessionMetadata(ctx: unknown): void {',
          '  updateSessionMetadata(ctx)',
          '}',
          '',
          'function getPostSessionMetadata(_ompRuntime: boolean): Record<string, unknown> {',
          '  return sessionMetadata',
          '}',
          ''
        ]
  // Why: Pi resumes from an existing transcript; OMP resumes directly by session id (#8962).
  const payloadLine =
    kind === 'pi'
      ? '    payload: { hook_event_name: hookEventName, ...(ompRuntime ? metadata : getPersistedSessionMetadata()), ...extra },'
      : '    payload: { hook_event_name: hookEventName, ...metadata, ...extra },'

  // Why: keep this string self-contained — it runs inside the pi process,
  // so it cannot import from Orca's main bundle. fs/http coords come from
  // the same endpoint file the OpenCode plugin reads (process.env is frozen
  // at PTY spawn, so on Orca restart we have to re-read it from disk).
  return [
    '// Why: no package-specific type import here. Pi and OMP expose the same',
    '// extension API, but publish their types under different package names.',
    '// Why: warn-once so a recurring parse error on a malformed endpoint',
    '// file does not spam stderr inside the pi TUI on every event.',
    'let warnedBadEndpoint = false',
    '// Why: Pi awaits extension handlers. Status delivery stays off that',
    '// critical path, and the latest-only pending slot prevents a stalled',
    '// Orca receiver from building an unbounded queue of obsolete snapshots.',
    'const HOOK_POST_TIMEOUT_MS = 1000',
    'let activePost = false',
    'let pendingPost: { hookEventName: string; extra: Record<string, unknown>; metadata: Record<string, unknown>; ompRuntime: boolean } | null = null',
    ...sessionMetadataSourceLines,
    '',
    '// Why: re-reading the endpoint file on every event is cheap (small file,',
    '// rare changes) but stat+mtime caching avoids re-parsing on every event',
    '// during streaming tool execution. Mirrors the OpenCode plugin cache shape.',
    "let cachedEndpointKey = ''",
    'let cachedEndpointValues: Record<string, string> | null = null',
    '',
    'function readEndpointFile(): Record<string, string> | null {',
    '  const path = process.env.ORCA_AGENT_HOOK_ENDPOINT',
    '  if (!path) return null',
    '  try {',
    "    const fs = require('fs')",
    '    try {',
    '      const stat = fs.statSync(path)',
    "      const cacheKey = stat.mtimeMs + ':' + stat.size + ':' + stat.ino",
    '      if (cacheKey === cachedEndpointKey && cachedEndpointValues) {',
    '        return cachedEndpointValues',
    '      }',
    "      const contents: string = fs.readFileSync(path, 'utf8')",
    '      const out: Record<string, string> = {}',
    '      for (const line of contents.split(/\\r?\\n/)) {',
    '        // Why: parse `KEY=VALUE` (POSIX endpoint.env) and `set KEY=VALUE`',
    '        // (Windows endpoint.cmd) with one regex; strip a trailing CR so',
    '        // mixed-EOL files do not leak \\r into the value.',
    '        const m = line.match(/^(?:set\\s+)?([A-Z0-9_]+)=(.*)$/)',
    "        if (m) out[m[1]] = m[2].replace(/\\r$/, '')",
    '      }',
    '      cachedEndpointKey = cacheKey',
    '      cachedEndpointValues = out',
    '      return out',
    '    } catch (ioErr) {',
    "      cachedEndpointKey = ''",
    '      cachedEndpointValues = null',
    '      throw ioErr',
    '    }',
    '  } catch (err: unknown) {',
    '    const code = (err as { code?: string } | null)?.code',
    "    if (err && code !== 'ENOENT' && !warnedBadEndpoint) {",
    '      warnedBadEndpoint = true',
    "      console.warn('[orca-pi-status] failed to parse endpoint file:', (err as Error).message)",
    '    }',
    '    return null',
    '  }',
    '}',
    '',
    'function resolveHookCoords() {',
    '  const fileEnv = readEndpointFile() || {}',
    '  return {',
    '    port: fileEnv.ORCA_AGENT_HOOK_PORT || process.env.ORCA_AGENT_HOOK_PORT,',
    '    token: fileEnv.ORCA_AGENT_HOOK_TOKEN || process.env.ORCA_AGENT_HOOK_TOKEN,',
    "    env: fileEnv.ORCA_AGENT_HOOK_ENV || process.env.ORCA_AGENT_HOOK_ENV || '',",
    "    version: fileEnv.ORCA_AGENT_HOOK_VERSION || process.env.ORCA_AGENT_HOOK_VERSION || '',",
    '  }',
    '}',
    '',
    ...getPiAgentStatusRuntimeDetectionSourceLines(kind),
    '',
    'function post(hookEventName: string, extra: Record<string, unknown> = {}): void {',
    '  const ompRuntime = isOmpRuntime()',
    '  pendingPost = {',
    '    hookEventName,',
    '    extra,',
    '    metadata: getPostSessionMetadata(ompRuntime),',
    '    ompRuntime,',
    '  }',
    '  drainPosts()',
    '}',
    '',
    'function drainPosts(): void {',
    '  if (activePost || !pendingPost) return',
    '  const next = pendingPost',
    '  pendingPost = null',
    '  activePost = true',
    '  void postOnce(next.hookEventName, next.extra, next.metadata, next.ompRuntime)',
    '    .catch(() => {})',
    '    .finally(() => {',
    '      activePost = false',
    '      drainPosts()',
    '    })',
    '}',
    '',
    'async function postOnce(',
    '  hookEventName: string,',
    '  extra: Record<string, unknown>,',
    '  metadata: Record<string, unknown>,',
    '  ompRuntime: boolean',
    '): Promise<void> {',
    '  const coords = resolveHookCoords()',
    '  const paneKey = process.env.ORCA_PANE_KEY',
    '  if (!coords.port || !coords.token || !paneKey) return',
    '  const url = `http://127.0.0.1:${coords.port}${resolveHookPath(ompRuntime)}`',
    '  const body = JSON.stringify({',
    '    paneKey,',
    "    launchToken: process.env.ORCA_AGENT_LAUNCH_TOKEN || '',",
    "    tabId: process.env.ORCA_TAB_ID || '',",
    "    worktreeId: process.env.ORCA_WORKTREE_ID || '',",
    '    env: coords.env,',
    '    version: coords.version,',
    payloadLine,
    '  })',
    "  const controller = typeof AbortController !== 'undefined' ? new AbortController() : null",
    '  let timeout: ReturnType<typeof setTimeout> | undefined',
    '  const timeoutPromise = new Promise<never>((_resolve, reject) => {',
    '    timeout = setTimeout(() => {',
    '      controller?.abort()',
    "      reject(new Error('Orca hook delivery timed out'))",
    '    }, HOOK_POST_TIMEOUT_MS)',
    "    if (typeof timeout.unref === 'function') timeout.unref()",
    '  })',
    '  try {',
    '    await Promise.race([',
    '      fetch(url, {',
    "        method: 'POST',",
    '        headers: {',
    "          'Content-Type': 'application/json',",
    "          'X-Orca-Agent-Hook-Token': coords.token,",
    '        },',
    '        body,',
    '        ...(controller ? { signal: controller.signal } : {}),',
    '      }),',
    '      timeoutPromise,',
    '    ])',
    '  } catch {',
    '    // Why: status reporting must never fail the pi run just because Orca',
    '    // is unavailable or the loopback request failed (e.g. Orca restart).',
    '    if (!isWslRuntime()) return',
    '    postViaWindowsCurl(url, coords, body)',
    '  } finally {',
    '    if (timeout) clearTimeout(timeout)',
    '  }',
    '}',
    '',
    '// Why: WSL-ness and curl.exe presence cannot change within a process',
    '// lifetime; re-probing /proc and /mnt/c on every failed event would add',
    '// filesystem work to the per-event path.',
    'let cachedIsWslRuntime: boolean | null = null',
    'let cachedWindowsCurlPath: string | null | undefined',
    '',
    'function isWslRuntime(): boolean {',
    '  if (cachedIsWslRuntime !== null) return cachedIsWslRuntime',
    '  cachedIsWslRuntime = detectWslRuntime()',
    '  return cachedIsWslRuntime',
    '}',
    '',
    'function detectWslRuntime(): boolean {',
    '  if (process.env.WSL_DISTRO_NAME) return true',
    '  try {',
    "    const fs = require('fs')",
    "    for (const path of ['/proc/sys/kernel/osrelease', '/proc/version']) {",
    '      try {',
    "        const contents = String(fs.readFileSync(path, 'utf8'))",
    '        if (/microsoft|wsl/i.test(contents)) return true',
    '      } catch {',
    '        // Why: probe the next runtime hint when a proc file is absent or unreadable.',
    '      }',
    '    }',
    '  } catch {',
    '    return false',
    '  }',
    '  return false',
    '}',
    '',
    'function resolveWindowsCurlPath(): string | null {',
    '  if (cachedWindowsCurlPath !== undefined) return cachedWindowsCurlPath',
    '  try {',
    "    const fs = require('fs')",
    "    const curlPath = '/mnt/c/Windows/System32/curl.exe'",
    '    cachedWindowsCurlPath = fs.existsSync(curlPath) ? curlPath : null',
    '  } catch {',
    '    cachedWindowsCurlPath = null',
    '  }',
    '  return cachedWindowsCurlPath',
    '}',
    '',
    '// Why: WSL loopback is not the Windows loopback, so a WSL-side POST cannot',
    '// reach Orca. curl.exe runs on the Windows side, where 127.0.0.1 IS the',
    '// listener Orca binds. Fire-and-forget: blocking on the spawn would stall',
    '// the pi event loop (and the TUI) on every hook event.',
    'function postViaWindowsCurl(url: string, coords: { token: string }, body: string): void {',
    '  const curlPath = resolveWindowsCurlPath()',
    '  if (!curlPath) return',
    '  try {',
    "    const { spawn } = require('child_process')",
    '    const child = spawn(',
    '      curlPath,',
    '      [',
    "        '-sS',",
    '        // Why: the spawn is detached from the event loop, so these bounds',
    '        // size a background process, not TUI latency. WSL->Win32 interop',
    '        // connects can exceed 0.5s on loaded machines (observed 3/3 drops',
    '        // to a healthy listener); size for delivery, not snappiness.',
    "        '--connect-timeout', '3',",
    "        '--max-time', '10',",
    "        '--noproxy', '127.0.0.1',",
    "        '-o', 'NUL',",
    "        '-X', 'POST',",
    "        '-H', 'Content-Type: application/json',",
    "        '-H', `X-Orca-Agent-Hook-Token: ${coords.token}`,",
    "        '--data-binary', '@-',",
    '        url',
    '      ],',
    "      { stdio: ['pipe', 'ignore', 'ignore'] }",
    '    )',
    "    child.on('error', () => {})",
    "    child.stdin.on('error', () => {})",
    '    child.stdin.end(body)',
    '  } catch {',
    '    // Why: the bridge is best-effort; a failed spawn must not surface',
    '    // inside the pi TUI.',
    '  }',
    '}',
    '',
    ...getPiAgentStatusHandlerSourceLines(kind)
  ].join('\n')
}
