// Why: agent harnesses (Claude Code and its forks) inject machinery into the
// conversation as user-role turns — background task notifications, system
// reminders, inter-agent messages, slash-command envelopes, local-command
// output, interruption and compaction notices. These fire user-prompt hooks
// and land in transcripts, but they are not something the user typed, so
// prompt-derived UI must not surface them.
//
// Every tag the harness injects is a lowercase multi-word kebab tag
// (<task-notification>, <agent-message from=…>, <cross-session-message>, …),
// so we match that shape instead of chasing individual tag names — the tag
// set grows faster than a literal list stays current. Underscore tags
// (<user_query>) are deliberately NOT matched: Grok wraps real typed prompts
// in them. This broad shape is limited to classification that does not remove
// transcript content; transcript filtering uses the observed-tag list below.
const HARNESS_KEBAB_TAG_PREFIX = /^<[a-z][a-z0-9]*(?:-[a-z0-9]+)+(?:[\s>]|$)/
const LEADING_TAG_NAME = /^<([a-z][a-z0-9-]*)(?:[\s>]|$)/

// Destructive consumers such as transcript filtering must only hide tags we
// have observed from harnesses; arbitrary kebab tags can be genuine user code.
const KNOWN_HARNESS_TAG_NAMES = new Set([
  'agent-message',
  'bash-input',
  'bash-stderr',
  'bash-stdout',
  'channel',
  'command-args',
  'command-message',
  'command-name',
  'cross-session-message',
  'fork-boilerplate',
  'local-command-caveat',
  'local-command-stderr',
  'local-command-stdout',
  'mcp-polling-update',
  'mcp-resource-update',
  'system-reminder',
  'task-notification',
  'teammate-message',
  'user-memory-input',
  'user-prompt-submit-hook'
])

// Injected shapes the kebab-tag rule cannot see: single-word attribute tags
// and the prose sentences the harness wraps deliveries and notices in.
const HARNESS_INJECTED_TURN_PREFIXES = [
  '<channel source=',
  '[request interrupted',
  'a message arrived from ',
  'another claude session sent a message',
  'no response requested.',
  'caveat: the messages below were generated by the user while running local commands',
  'this session is being continued from a previous conversation'
]

/** True when prompt-like text is a harness-injected machinery turn rather
 *  than something the user typed. Match on trimmed, lowercased text. */
export function isHarnessInjectedUserTurnText(text: string): boolean {
  const normalized = text.trim().toLowerCase()
  if (normalized.length === 0) {
    return false
  }
  if (HARNESS_KEBAB_TAG_PREFIX.test(normalized)) {
    return true
  }
  return HARNESS_INJECTED_TURN_PREFIXES.some((prefix) => normalized.startsWith(prefix))
}

/** True only for observed harness shapes. Use this when a match removes user
 *  content rather than merely suppressing ephemeral prompt-derived UI. */
export function isKnownHarnessInjectedUserTurnText(text: string): boolean {
  const normalized = text.trim().toLowerCase()
  if (normalized.length === 0) {
    return false
  }
  const tagName = LEADING_TAG_NAME.exec(normalized)?.[1]
  if (tagName && KNOWN_HARNESS_TAG_NAMES.has(tagName)) {
    return true
  }
  return HARNESS_INJECTED_TURN_PREFIXES.some((prefix) => normalized.startsWith(prefix))
}
