import { describe, expect, it } from 'vitest'

import {
  isHarnessInjectedUserTurnText,
  isKnownHarnessInjectedUserTurnText
} from './harness-injected-user-turns'

describe('isHarnessInjectedUserTurnText', () => {
  it('matches every known harness tag, including attribute-carrying forms', () => {
    // Inventory mirrors the tags the harness itself classifies as machinery.
    const injected = [
      '<task-notification> <task-id>bzthj2b8r</task-id> <tool-use-id>toolu_01abc</tool-use-id>',
      '<task-notification summary="Agent finished">',
      '<system-reminder>context</system-reminder>',
      '<agent-message from="reviewer-A-r3b"> REVIEW the diff',
      '<teammate-message teammate_id="worker-1">status?',
      '<cross-session-message from="other session">hello',
      '<channel source="general">new post',
      '<fork-boilerplate>Your directive: ship it',
      '<user-memory-input>remember this',
      '<mcp-resource-update uri="db://x">',
      '<mcp-polling-update>tick',
      '<command-name>/review</command-name>',
      '<command-message>review</command-message>',
      '<command-args>--fix</command-args>',
      '<local-command-stdout>ok</local-command-stdout>',
      '<local-command-stderr>boom</local-command-stderr>',
      '<local-command-caveat>Caveat: tool output</local-command-caveat>',
      '<bash-input>ls</bash-input>',
      '<bash-stdout>file.txt</bash-stdout>',
      '<bash-stderr>err</bash-stderr>',
      '<user-prompt-submit-hook>hook context</user-prompt-submit-hook>'
    ]
    for (const text of injected) {
      expect(isHarnessInjectedUserTurnText(text), text).toBe(true)
      expect(isKnownHarnessInjectedUserTurnText(text), text).toBe(true)
    }
  })

  it('matches future kebab tags without a list update', () => {
    expect(isHarnessInjectedUserTurnText('<brand-new-harness-tag id="1">payload')).toBe(true)
    expect(isHarnessInjectedUserTurnText('<queued-notice>\nlater')).toBe(true)
  })

  it('matches harness prose wrappers and notices', () => {
    expect(
      isHarnessInjectedUserTurnText('A message arrived from teammate-b:\n<agent-message>hi')
    ).toBe(true)
    expect(
      isHarnessInjectedUserTurnText('Another Claude session sent a message:\n<agent-message>hi')
    ).toBe(true)
    expect(isHarnessInjectedUserTurnText('No response requested.')).toBe(true)
    expect(isHarnessInjectedUserTurnText('[Request interrupted by user]')).toBe(true)
    expect(isHarnessInjectedUserTurnText('[Request interrupted by user for tool use]')).toBe(true)
    expect(
      isHarnessInjectedUserTurnText('This session is being continued from a previous conversation.')
    ).toBe(true)
    expect(
      isHarnessInjectedUserTurnText(
        'Caveat: the messages below were generated by the user while running local commands.'
      )
    ).toBe(true)
  })

  it('is case-insensitive and ignores surrounding whitespace', () => {
    expect(isHarnessInjectedUserTurnText('  <TASK-NOTIFICATION> done')).toBe(true)
    expect(isHarnessInjectedUserTurnText('\n<System-Reminder> hi')).toBe(true)
  })

  it('keeps real user prompts, including ones that mention the tags', () => {
    expect(isHarnessInjectedUserTurnText('fix the login bug')).toBe(false)
    expect(isHarnessInjectedUserTurnText('why does <task-notification> show in the sidebar?')).toBe(
      false
    )
    expect(isHarnessInjectedUserTurnText('')).toBe(false)
    expect(isHarnessInjectedUserTurnText('   ')).toBe(false)
  })

  it('keeps single-word tag pastes and underscore wrappers', () => {
    // Grok wraps REAL typed prompts in <user_query> — never classify as noise.
    expect(isHarnessInjectedUserTurnText('<user_query>fix the bug</user_query>')).toBe(false)
    expect(isHarnessInjectedUserTurnText('<div class="x">pasted html</div>')).toBe(false)
    expect(isHarnessInjectedUserTurnText('<script>alert(1)</script> — why is this flagged?')).toBe(
      false
    )
    expect(isHarnessInjectedUserTurnText('<https://example.com/a-b> what is this?')).toBe(false)
    expect(isHarnessInjectedUserTurnText('<foo-bar@example.com> sent me this')).toBe(false)
  })

  it('limits destructive filtering to observed harness tags', () => {
    expect(isKnownHarnessInjectedUserTurnText('<task-notification>done')).toBe(true)
    expect(isKnownHarnessInjectedUserTurnText('<agent-message from="worker">done')).toBe(true)
    expect(isKnownHarnessInjectedUserTurnText('<my-custom-element>pasted code')).toBe(false)
    expect(isKnownHarnessInjectedUserTurnText('<brand-new-harness-tag>unknown')).toBe(false)
  })
})
