export const PR_REFRESH_QUEUE_ENTRY_LIMIT = 1_024
export const PR_REFRESH_ALIAS_LIMIT = 64
export const PR_REFRESH_VISIBLE_CANDIDATE_LIMIT = 1_024
export const PR_REFRESH_RETRY_STATE_LIMIT = 1_024
export const PR_REFRESH_ACTIVE_SCOPE_LIMIT = 1_024
